### ISSUE TITLE
嗨朋友，有没有兴趣将你这个项目贡献到 jap 组织下？

### ISSUE THREAD

**Issue by zhangyd-c** [fujieid/medusa-auth-sso#1]
https://github.com/fujieid

https://gitee.com/fujieid

**Comment by apicescn** [comment]
有的，不过怎么联系呢？

**Comment by zhangyd-c** [comment]
我就是作者啊😀，加我微信吧，justauth

**Comment by zhangyd-c** [comment]
你可以这么操作，进入你这儿项目的 setting 目录，然后直接拉到最下面，有个 “Transfer ownership” 选项

![image](https://user-images.githubusercontent.com/12689082/140487823-abd90991-f4f7-400a-afe4-fd71b01cb830.png)

![image](https://user-images.githubusercontent.com/12689082/140487893-23b93cbf-26d7-4301-887c-3e8b831fc7d1.png)

然后加我好友，建立个联系，你回复我一下，然后我把我微信号的那条回复删除掉

**Comment by apicescn** [comment]
已操作！
